-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.app_users (
  id uuid NOT NULL,
  name text NOT NULL,
  email text UNIQUE,
  role USER-DEFINED NOT NULL DEFAULT 'member'::erp_role,
  bu_code USER-DEFINED,
  position text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT app_users_pkey PRIMARY KEY (id),
  CONSTRAINT app_users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.artists (
  id bigint NOT NULL DEFAULT nextval('artists_id_seq'::regclass),
  bu_code USER-DEFINED NOT NULL,
  name text NOT NULL,
  nationality text,
  visa_type text,
  contract_start date NOT NULL,
  contract_end date NOT NULL,
  visa_start date,
  visa_end date,
  role text,
  status text NOT NULL DEFAULT 'Active'::text CHECK (status = ANY (ARRAY['Active'::text, 'Inactive'::text, 'Archived'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  type text NOT NULL DEFAULT 'individual'::text CHECK (type = ANY (ARRAY['individual'::text, 'team'::text])),
  team_id bigint,
  CONSTRAINT artists_pkey PRIMARY KEY (id),
  CONSTRAINT artists_bu_code_fkey FOREIGN KEY (bu_code) REFERENCES public.business_units(code),
  CONSTRAINT artists_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.artists(id)
);
CREATE TABLE public.business_units (
  id bigint NOT NULL DEFAULT nextval('business_units_id_seq'::regclass),
  code USER-DEFINED NOT NULL UNIQUE,
  name text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT business_units_pkey PRIMARY KEY (id)
);
CREATE TABLE public.channel_contents (
  id bigint NOT NULL DEFAULT nextval('channel_contents_id_seq'::regclass),
  channel_id bigint NOT NULL,
  title text NOT NULL,
  stage USER-DEFINED NOT NULL DEFAULT 'planning'::content_stage,
  assignee_id uuid,
  assignee_name text,
  upload_date date NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT channel_contents_pkey PRIMARY KEY (id),
  CONSTRAINT channel_contents_channel_id_fkey FOREIGN KEY (channel_id) REFERENCES public.channels(id),
  CONSTRAINT channel_contents_assignee_id_fkey FOREIGN KEY (assignee_id) REFERENCES public.app_users(id)
);
CREATE TABLE public.channels (
  id bigint NOT NULL DEFAULT nextval('channels_id_seq'::regclass),
  bu_code USER-DEFINED NOT NULL,
  name text NOT NULL,
  url text,
  subscribers_count text,
  total_views text,
  status USER-DEFINED NOT NULL DEFAULT 'active'::channel_status,
  manager_id uuid,
  manager_name text,
  next_upload_date date,
  recent_video text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  production_company text,
  ad_status text DEFAULT 'none'::text CHECK (ad_status = ANY (ARRAY['active'::text, 'paused'::text, 'completed'::text, 'none'::text])),
  upload_days ARRAY,
  CONSTRAINT channels_pkey PRIMARY KEY (id),
  CONSTRAINT channels_bu_code_fkey FOREIGN KEY (bu_code) REFERENCES public.business_units(code),
  CONSTRAINT channels_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES public.app_users(id)
);
CREATE TABLE public.client_company (
  id bigint NOT NULL DEFAULT nextval('client_company_id_seq'::regclass),
  bu_code USER-DEFINED NOT NULL,
  company_name_en text,
  company_name_ko text,
  industry text,
  business_registration_number text,
  representative_name text,
  status USER-DEFINED NOT NULL DEFAULT 'active'::client_status,
  last_meeting_date date,
  business_registration_file text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT client_company_pkey PRIMARY KEY (id),
  CONSTRAINT client_company_bu_code_fkey FOREIGN KEY (bu_code) REFERENCES public.business_units(code)
);
CREATE TABLE public.client_worker (
  id bigint NOT NULL DEFAULT nextval('client_worker_id_seq'::regclass),
  client_company_id bigint,
  name_en text,
  name_ko text,
  phone text,
  email text,
  business_card_file text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT client_worker_pkey PRIMARY KEY (id),
  CONSTRAINT client_worker_client_company_id_fkey FOREIGN KEY (client_company_id) REFERENCES public.client_company(id)
);
CREATE TABLE public.comment_mentions_reads (
  id bigint NOT NULL DEFAULT nextval('comment_mentions_reads_id_seq'::regclass),
  comment_id bigint NOT NULL,
  user_id uuid NOT NULL,
  read_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT comment_mentions_reads_pkey PRIMARY KEY (id),
  CONSTRAINT comment_mentions_reads_comment_id_fkey FOREIGN KEY (comment_id) REFERENCES public.comments(id),
  CONSTRAINT comment_mentions_reads_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(id)
);
CREATE TABLE public.comments (
  id bigint NOT NULL DEFAULT nextval('comments_id_seq'::regclass),
  entity_type text NOT NULL CHECK (entity_type = ANY (ARRAY['task'::text, 'project'::text])),
  entity_id bigint NOT NULL,
  content text NOT NULL,
  author_id uuid NOT NULL,
  author_name text NOT NULL,
  mentioned_user_ids jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT comments_pkey PRIMARY KEY (id),
  CONSTRAINT comments_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.app_users(id)
);
CREATE TABLE public.creators (
  id bigint NOT NULL DEFAULT nextval('creators_id_seq'::regclass),
  bu_code USER-DEFINED NOT NULL,
  name text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['creator'::text, 'celebrity'::text, 'influencer'::text])),
  platform text,
  channel_id bigint,
  subscribers_count text,
  engagement_rate text,
  contact_person text,
  phone text,
  email text,
  agency text,
  fee_range text,
  specialties ARRAY,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'archived'::text])),
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT creators_pkey PRIMARY KEY (id),
  CONSTRAINT creators_bu_code_fkey FOREIGN KEY (bu_code) REFERENCES public.business_units(code),
  CONSTRAINT creators_channel_id_fkey FOREIGN KEY (channel_id) REFERENCES public.channels(id),
  CONSTRAINT creators_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.app_users(id)
);
CREATE TABLE public.equipment (
  id bigint NOT NULL DEFAULT nextval('equipment_id_seq'::regclass),
  bu_code USER-DEFINED NOT NULL,
  name text NOT NULL,
  category text NOT NULL,
  serial_number text,
  status USER-DEFINED NOT NULL DEFAULT 'available'::equipment_status,
  location text,
  borrower_id uuid,
  borrower_name text,
  return_date date,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT equipment_pkey PRIMARY KEY (id),
  CONSTRAINT equipment_bu_code_fkey FOREIGN KEY (bu_code) REFERENCES public.business_units(code),
  CONSTRAINT equipment_borrower_id_fkey FOREIGN KEY (borrower_id) REFERENCES public.app_users(id)
);
CREATE TABLE public.events (
  id bigint NOT NULL DEFAULT nextval('events_id_seq'::regclass),
  bu_code USER-DEFINED NOT NULL,
  title text NOT NULL,
  event_date date NOT NULL,
  event_type USER-DEFINED NOT NULL DEFAULT 'event'::event_type,
  description text,
  project_id bigint,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT events_pkey PRIMARY KEY (id),
  CONSTRAINT events_bu_code_fkey FOREIGN KEY (bu_code) REFERENCES public.business_units(code),
  CONSTRAINT events_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT events_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.app_users(id)
);
CREATE TABLE public.external_workers (
  id bigint NOT NULL DEFAULT nextval('external_workers_id_seq'::regclass),
  bu_code USER-DEFINED NOT NULL,
  name text NOT NULL,
  company_name text,
  worker_type text NOT NULL DEFAULT 'freelancer'::text CHECK (worker_type = ANY (ARRAY['freelancer'::text, 'company'::text, 'contractor'::text])),
  phone text,
  email text,
  specialties ARRAY,
  notes text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT external_workers_pkey PRIMARY KEY (id),
  CONSTRAINT external_workers_bu_code_fkey FOREIGN KEY (bu_code) REFERENCES public.business_units(code)
);
CREATE TABLE public.financial_entries (
  id bigint NOT NULL DEFAULT nextval('financial_entries_id_seq'::regclass),
  project_id bigint NOT NULL,
  bu_code USER-DEFINED NOT NULL,
  kind USER-DEFINED NOT NULL,
  category text NOT NULL,
  name text NOT NULL,
  amount bigint NOT NULL CHECK (amount >= 0),
  occurred_at date NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'planned'::financial_status,
  memo text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT financial_entries_pkey PRIMARY KEY (id),
  CONSTRAINT financial_entries_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT financial_entries_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.app_users(id)
);
CREATE TABLE public.manuals (
  id bigint NOT NULL DEFAULT nextval('manuals_id_seq'::regclass),
  bu_code USER-DEFINED NOT NULL,
  title text NOT NULL,
  category text NOT NULL,
  content jsonb NOT NULL DEFAULT '[]'::jsonb,
  author_id uuid,
  author_name text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT manuals_pkey PRIMARY KEY (id),
  CONSTRAINT manuals_bu_code_fkey FOREIGN KEY (bu_code) REFERENCES public.business_units(code),
  CONSTRAINT manuals_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.app_users(id)
);
CREATE TABLE public.org_members (
  id bigint NOT NULL DEFAULT nextval('org_members_id_seq'::regclass),
  org_unit_id bigint,
  name text NOT NULL,
  title text,
  user_id uuid,
  is_leader boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  bu_code USER-DEFINED,
  phone text,
  email text,
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT org_members_pkey PRIMARY KEY (id),
  CONSTRAINT org_members_org_unit_id_fkey FOREIGN KEY (org_unit_id) REFERENCES public.org_units(id),
  CONSTRAINT org_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(id)
);
CREATE TABLE public.org_units (
  id bigint NOT NULL DEFAULT nextval('org_units_id_seq'::regclass),
  name text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT org_units_pkey PRIMARY KEY (id)
);
CREATE TABLE public.project_tasks (
  id bigint NOT NULL DEFAULT nextval('project_tasks_id_seq'::regclass),
  project_id bigint NOT NULL,
  bu_code USER-DEFINED NOT NULL,
  title text NOT NULL,
  assignee_id uuid,
  assignee text,
  due_date date NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'todo'::task_status,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  priority text DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text])),
  tag text,
  CONSTRAINT project_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT project_tasks_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT project_tasks_assignee_id_fkey FOREIGN KEY (assignee_id) REFERENCES public.app_users(id),
  CONSTRAINT project_tasks_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.app_users(id)
);
CREATE TABLE public.projects (
  id bigint NOT NULL DEFAULT nextval('projects_id_seq'::regclass),
  bu_code USER-DEFINED NOT NULL,
  name text NOT NULL,
  category text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT '준비중'::project_status,
  start_date date,
  end_date date,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  client_id bigint,
  creators jsonb DEFAULT '[]'::jsonb,
  freelancers jsonb DEFAULT '[]'::jsonb,
  artist_id bigint,
  pm_name text,
  active_steps jsonb DEFAULT '[]'::jsonb,
  plan_date date,
  script_date date,
  shoot_date date,
  edit1_date date,
  edit_final_date date,
  release_date date,
  assets jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT projects_pkey PRIMARY KEY (id),
  CONSTRAINT projects_bu_code_fkey FOREIGN KEY (bu_code) REFERENCES public.business_units(code),
  CONSTRAINT projects_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.app_users(id),
  CONSTRAINT projects_artist_id_fkey FOREIGN KEY (artist_id) REFERENCES public.artists(id),
  CONSTRAINT fk_projects_client_company_id FOREIGN KEY (client_id) REFERENCES public.client_company(id)
);