-- 1. comments 테이블의 entity_type 체크 제약조건 수정 (financial 추가)
ALTER TABLE comments DROP CONSTRAINT IF EXISTS comments_entity_type_check;
ALTER TABLE comments ADD CONSTRAINT comments_entity_type_check 
  CHECK (entity_type = ANY (ARRAY['task'::text, 'project'::text, 'financial'::text]));

-- 2. comment_attachments 테이블 생성
CREATE TABLE IF NOT EXISTS comment_attachments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comment_id BIGINT NOT NULL REFERENCES comments(id) ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  file_path TEXT NOT NULL,
  file_type TEXT NOT NULL,
  file_size BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 인덱스 추가
CREATE INDEX IF NOT EXISTS idx_comment_attachments_comment_id ON comment_attachments(comment_id);

-- updated_at 트리거 생성
CREATE OR REPLACE FUNCTION update_comment_attachments_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_comment_attachments_updated_at_trigger ON comment_attachments;
CREATE TRIGGER update_comment_attachments_updated_at_trigger
  BEFORE UPDATE ON comment_attachments
  FOR EACH ROW
  EXECUTE FUNCTION update_comment_attachments_updated_at();

-- 테이블 코멘트
COMMENT ON TABLE comment_attachments IS '댓글 첨부파일 - 이미지, PDF 등의 파일을 댓글에 첨부';
COMMENT ON COLUMN comment_attachments.file_name IS '원본 파일명';
COMMENT ON COLUMN comment_attachments.file_path IS 'Supabase Storage 내 파일 경로';
COMMENT ON COLUMN comment_attachments.file_type IS 'MIME type (예: image/png, application/pdf)';
COMMENT ON COLUMN comment_attachments.file_size IS '파일 크기 (bytes)';

-- 3. Storage bucket 생성 (comment-attachments)
-- 이 부분은 Supabase Dashboard에서 직접 생성하거나 아래 SQL을 사용
-- INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
-- VALUES (
--   'comment-attachments',
--   'comment-attachments',
--   true,
--   10485760, -- 10MB
--   ARRAY['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']
-- )
-- ON CONFLICT (id) DO NOTHING;
