-- 자료실(document_room): 사업자등록증, 통장사본, 소개서 등 회사 공용 서류 업로드/다운로드
-- category: business_registration(사업자등록증), bank_copy(통장사본), introduction(소개서), other(기타)

CREATE TABLE IF NOT EXISTS document_room_files (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL CHECK (category IN ('business_registration', 'bank_copy', 'introduction', 'other')),
  file_name TEXT NOT NULL,
  file_path TEXT NOT NULL,
  file_size BIGINT NOT NULL DEFAULT 0,
  mime_type TEXT,
  created_by UUID REFERENCES app_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_document_room_files_category ON document_room_files(category);
CREATE INDEX IF NOT EXISTS idx_document_room_files_created_at ON document_room_files(created_at DESC);

CREATE OR REPLACE FUNCTION update_document_room_files_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_document_room_files_updated_at_trigger ON document_room_files;
CREATE TRIGGER update_document_room_files_updated_at_trigger
  BEFORE UPDATE ON document_room_files
  FOR EACH ROW
  EXECUTE FUNCTION update_document_room_files_updated_at();

COMMENT ON TABLE document_room_files IS '자료실 - 사업자등록증, 통장사본, 소개서 등 회사 공용 서류';
COMMENT ON COLUMN document_room_files.category IS '분류: business_registration(사업자등록증), bank_copy(통장사본), introduction(소개서), other(기타)';
COMMENT ON COLUMN document_room_files.file_path IS 'Supabase Storage bucket document-room 내 경로';

-- Storage 버킷 생성: Supabase Dashboard > Storage > New bucket > 이름: document-room, Public: false 권장.
-- 또는 SQL: INSERT INTO storage.buckets (id, name, public) VALUES ('document-room', 'document-room', false) ON CONFLICT (id) DO NOTHING;
