-- Leave Management System Migration
-- 연차/휴가 관리 시스템 테이블 생성

-- 1. Enum Types
DO $$ BEGIN
    CREATE TYPE leave_type AS ENUM ('annual', 'compensatory', 'special');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE leave_request_type AS ENUM ('annual', 'half_am', 'half_pm', 'compensatory', 'special');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE leave_grant_type AS ENUM ('auto_monthly', 'auto_yearly', 'manual', 'compensatory_approved');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 2. Add hire_date column to app_users
ALTER TABLE app_users 
ADD COLUMN IF NOT EXISTS hire_date date;

COMMENT ON COLUMN app_users.hire_date IS '입사일 (연차 자동 생성 기준)';

-- 3. Leave Balances Table (사용자별 연도별 휴가 잔여일수)
CREATE TABLE IF NOT EXISTS leave_balances (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    leave_type leave_type NOT NULL,
    total_days numeric(5,1) NOT NULL DEFAULT 0,
    used_days numeric(5,1) NOT NULL DEFAULT 0,
    year integer NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    UNIQUE(user_id, leave_type, year),
    CONSTRAINT positive_total_days CHECK (total_days >= 0),
    CONSTRAINT positive_used_days CHECK (used_days >= 0),
    CONSTRAINT used_not_exceed_total CHECK (used_days <= total_days)
);

COMMENT ON TABLE leave_balances IS '사용자별 연도별 휴가 잔여일수';
COMMENT ON COLUMN leave_balances.leave_type IS 'annual(연차), compensatory(대체휴무), special(특별휴가)';
COMMENT ON COLUMN leave_balances.total_days IS '총 부여된 휴가 일수';
COMMENT ON COLUMN leave_balances.used_days IS '사용한 휴가 일수';
COMMENT ON COLUMN leave_balances.year IS '해당 연도';

-- 4. Leave Grants Table (휴가 부여 이력)
CREATE TABLE IF NOT EXISTS leave_grants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    leave_type leave_type NOT NULL,
    days numeric(5,1) NOT NULL,
    grant_type leave_grant_type NOT NULL,
    reason text,
    granted_by uuid REFERENCES app_users(id) ON DELETE SET NULL,
    year integer NOT NULL,
    granted_at timestamp with time zone DEFAULT now(),
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT positive_grant_days CHECK (days > 0)
);

COMMENT ON TABLE leave_grants IS '휴가 부여 이력 (자동/수동)';
COMMENT ON COLUMN leave_grants.grant_type IS 'auto_monthly(월별 자동), auto_yearly(연간 자동), manual(관리자 수동), compensatory_approved(대체휴무 승인)';
COMMENT ON COLUMN leave_grants.reason IS '부여 사유 (예: 야근 대체, 특별 포상 등)';

-- 5. Leave Requests Table (휴가 사용 신청)
CREATE TABLE IF NOT EXISTS leave_requests (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    requester_id uuid NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    leave_type leave_request_type NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    days_used numeric(5,1) NOT NULL,
    reason text NOT NULL,
    status approval_status NOT NULL DEFAULT 'pending',
    approver_id uuid REFERENCES app_users(id) ON DELETE SET NULL,
    rejection_reason text,
    approved_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT valid_date_range CHECK (end_date >= start_date),
    CONSTRAINT positive_days_used CHECK (days_used > 0)
);

COMMENT ON TABLE leave_requests IS '휴가 사용 신청';
COMMENT ON COLUMN leave_requests.leave_type IS 'annual(연차), half_am(오전반차), half_pm(오후반차), compensatory(대체휴무), special(특별휴가)';
COMMENT ON COLUMN leave_requests.days_used IS '사용 일수 (반차=0.5, 연차=1)';
COMMENT ON COLUMN leave_requests.status IS 'pending(대기), approved(승인), rejected(반려)';

-- 6. Compensatory Leave Requests Table (대체휴무 생성 신청)
CREATE TABLE IF NOT EXISTS compensatory_requests (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    requester_id uuid NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    days numeric(5,1) NOT NULL DEFAULT 1,
    reason text NOT NULL,
    work_date date,
    status approval_status NOT NULL DEFAULT 'pending',
    approver_id uuid REFERENCES app_users(id) ON DELETE SET NULL,
    rejection_reason text,
    approved_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT positive_comp_days CHECK (days > 0)
);

COMMENT ON TABLE compensatory_requests IS '대체휴무 생성 신청';
COMMENT ON COLUMN compensatory_requests.work_date IS '대체휴무 발생 사유가 된 근무일 (예: 휴일 근무일)';
COMMENT ON COLUMN compensatory_requests.reason IS '대체휴무 생성 사유 (예: 1/15 휴일 근무)';

-- 7. Indexes for performance
CREATE INDEX IF NOT EXISTS idx_leave_balances_user_year ON leave_balances(user_id, year);
CREATE INDEX IF NOT EXISTS idx_leave_grants_user_year ON leave_grants(user_id, year);
CREATE INDEX IF NOT EXISTS idx_leave_requests_requester ON leave_requests(requester_id);
CREATE INDEX IF NOT EXISTS idx_leave_requests_status ON leave_requests(status);
CREATE INDEX IF NOT EXISTS idx_leave_requests_dates ON leave_requests(start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_compensatory_requests_requester ON compensatory_requests(requester_id);
CREATE INDEX IF NOT EXISTS idx_compensatory_requests_status ON compensatory_requests(status);

-- 8. Triggers for updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_leave_balances_updated_at ON leave_balances;
CREATE TRIGGER update_leave_balances_updated_at
    BEFORE UPDATE ON leave_balances
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_leave_requests_updated_at ON leave_requests;
CREATE TRIGGER update_leave_requests_updated_at
    BEFORE UPDATE ON leave_requests
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_compensatory_requests_updated_at ON compensatory_requests;
CREATE TRIGGER update_compensatory_requests_updated_at
    BEFORE UPDATE ON compensatory_requests
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 9. RLS Policies
ALTER TABLE leave_balances ENABLE ROW LEVEL SECURITY;
ALTER TABLE leave_grants ENABLE ROW LEVEL SECURITY;
ALTER TABLE leave_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE compensatory_requests ENABLE ROW LEVEL SECURITY;

-- Leave Balances: 본인 또는 관리자만 조회 가능
CREATE POLICY "Users can view own leave balances" ON leave_balances
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Admins can view all leave balances" ON leave_balances
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM app_users 
            WHERE id = auth.uid() 
            AND role IN ('admin', 'leader')
        )
    );

CREATE POLICY "Admins can manage leave balances" ON leave_balances
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM app_users 
            WHERE id = auth.uid() 
            AND role = 'admin' 
            AND bu_code = 'HEAD'
        )
    );

-- Leave Grants: 관리자만 생성 가능, 본인 또는 관리자 조회 가능
CREATE POLICY "Users can view own leave grants" ON leave_grants
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Admins can view all leave grants" ON leave_grants
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM app_users 
            WHERE id = auth.uid() 
            AND role IN ('admin', 'leader')
        )
    );

CREATE POLICY "HEAD Admins can manage leave grants" ON leave_grants
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM app_users 
            WHERE id = auth.uid() 
            AND role = 'admin' 
            AND bu_code = 'HEAD'
        )
    );

-- Leave Requests: 본인 생성, 본인/관리자 조회, 관리자 승인
CREATE POLICY "Users can create own leave requests" ON leave_requests
    FOR INSERT WITH CHECK (auth.uid() = requester_id);

CREATE POLICY "Users can view own leave requests" ON leave_requests
    FOR SELECT USING (auth.uid() = requester_id);

CREATE POLICY "Leaders can view BU leave requests" ON leave_requests
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM app_users au
            JOIN app_users req ON req.id = leave_requests.requester_id
            WHERE au.id = auth.uid() 
            AND au.role = 'leader'
            AND au.bu_code = req.bu_code
        )
    );

CREATE POLICY "Admins can view all leave requests" ON leave_requests
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM app_users 
            WHERE id = auth.uid() 
            AND role = 'admin'
        )
    );

CREATE POLICY "Leaders and Admins can update leave requests" ON leave_requests
    FOR UPDATE USING (
        EXISTS (
            SELECT 1 FROM app_users 
            WHERE id = auth.uid() 
            AND role IN ('admin', 'leader')
        )
    );

-- Compensatory Requests: 본인 생성, 본인/관리자 조회, HEAD admin만 승인
CREATE POLICY "Users can create own compensatory requests" ON compensatory_requests
    FOR INSERT WITH CHECK (auth.uid() = requester_id);

CREATE POLICY "Users can view own compensatory requests" ON compensatory_requests
    FOR SELECT USING (auth.uid() = requester_id);

CREATE POLICY "Admins can view all compensatory requests" ON compensatory_requests
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM app_users 
            WHERE id = auth.uid() 
            AND role IN ('admin', 'leader')
        )
    );

CREATE POLICY "HEAD Admins can update compensatory requests" ON compensatory_requests
    FOR UPDATE USING (
        EXISTS (
            SELECT 1 FROM app_users 
            WHERE id = auth.uid() 
            AND role = 'admin' 
            AND bu_code = 'HEAD'
        )
    );
